TaskManager.Web/Controllers/NodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BSF.Db;
using TaskManager.Web.Models;
using TaskManager.Domain.Dal;
using TaskManager.Domain.Model;
using Webdiyer.WebControls.Mvc;
using TaskManager.Core.Net;
using TaskManager.Core;
using TaskManager.Core;

namespace TaskManager.Web.Controllers
{
    [AuthorityCheck]
    public class NodeController : BaseWebController
    {
        //
        // GET: /Node/

        public ActionResult Index(string keyword, string CStime, string CEtime, int pagesize = 10, int pageindex = 1)
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                ViewBag.sqldatetimenow = DateTime.Now;
                tb_node_dal dal = new tb_node_dal();
                Webdiyer.WebControls.Mvc.PagedList<tb_node_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_node_model> List = dal.GetList(PubConn, keyword, CStime, CEtime, pagesize, pageindex, out count);
                    pageList = new PagedList<tb_node_model>(List, pageindex, pagesize, count);
                    ViewBag.sqldatetimenow = PubConn.GetServerDate();
                }
                return View(pageList);
            });
        }

        public ActionResult Add()
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                return View();
            });
        }

        [HttpPost]
        public ActionResult Add(tb_node_model model)
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                tb_node_dal Dal = new tb_node_dal();
                model.nodecreatetime = DateTime.Now;
                model.nodelastupdatetime = DateTime.Now;
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    Dal.AddOrUpdate(PubConn, model);
                }
                return RedirectToAction("index");
            });
        }

        public ActionResult Update(int id)
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                tb_node_dal dal = new tb_node_dal();
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    tb_node_model model = dal.GetOneNode(PubConn, id);
                    return View(model);
                }
            });
        }

        [HttpPost]
        public ActionResult Update(tb_node_model model)
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                tb_node_dal Dal = new tb_node_dal();
                model.nodecreatetime = DateTime.Now;
                model.nodelastupdatetime = DateTime.Now;
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    Dal.Update(PubConn, model);
                }
                return RedirectToAction("index");
            });
        }

        public JsonResult Delete(int id)
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                try
                {
                    tb_node_dal dal = new tb_node_dal();
                    using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                    {
                        PubConn.Open();
                        bool state = dal.DeleteOneNode(PubConn, id);
                        return Json(new { code = 1, state = state });
                    }
                }
                catch (Exception ex)
                {
                    return Json(new { code = -1, msg = ex.Message });
                }
            });
        }

        
    }
}

TaskManager.Web/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Domain.Model;
using TaskManager.Domain.Dal;
using BSF.Db;
using TaskManager.Web.Models;
using Webdiyer.WebControls.Mvc;
using System.Drawing;
using System.IO;
using TaskManager.Core;
using BSF.Extensions;
using Newtonsoft.Json;
using TaskManager.Core;
using TaskManager.Web.Tools;

namespace TaskManager.Web.Controllers
{
    [AuthorityCheck]
    public class TaskController : BaseWebController
    {
        //
        // GET: /Task/

        public ActionResult Index(string taskid, string keyword, string CStime, string CEtime, int categoryid = -1, int nodeid = -1, int userid = -1, int state = -999, int pagesize = 10, int pageindex = 1)
        {
            return this.Visit(EnumUserRole.None, () =>
            {
                #region 保存查询信息,优化操作体验
                var ps = Request.RequestParams();
                ps.Remove("userid");
                var sessionkey = "/task/index/";
                if (ps.Count == 0)
                {
                    if (Session[sessionkey] != null)
                    {
                        var ks = new BSF.Serialization.JsonProvider( BSF.Serialization.JsonAdapter.EnumJsonMode.Newtonsoft).Deserialize<List<KeyValuePair<string,object>>>(Session[sessionkey] as string);
                        foreach (var k in ks)
                        {
                            if(!ViewData.ContainsKey(k.Key))
                                ViewData.Add(k);
                        }
                        taskid = (string)ViewBag.taskid;
                        keyword =(string) ViewBag.keyword;
                        CStime = (string)ViewBag.CStime;
                        CEtime = (string) ViewBag.CEtime;
                        categoryid = (int)ViewBag.categoryid;
                        nodeid = (int)ViewBag.nodeid;
                        userid = (int)ViewBag.userid;
                        state = (int)ViewBag.state;
                        pagesize = (int)ViewBag.pagesize;
                        pageindex = (int)ViewBag.pageindex;
                    }
                }
                ViewBag.taskid = taskid;
                ViewBag.keyword = keyword;
                ViewBag.CStime = CStime;
                ViewBag.CEtime = CEtime;
                ViewBag.categoryid = categoryid;
                ViewBag.nodeid = nodeid;
                ViewBag.userid = userid;
                ViewBag.state = state;
                ViewBag.pagesize = pagesize;
                ViewBag.pageindex = pageindex;

                Session[sessionkey] = new BSF.Serialization.JsonProvider().Serializer(ViewData);
                #endregion

                tb_task_dal dal = new tb_task_dal();
                PagedList<tb_tasklist_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_tasklist_model> List = dal.GetList(PubConn, taskid, keyword, CStime, CEtime, categoryid, nodeid, userid, state, pagesize, pageindex, out count);
                    pageList = new PagedList<tb_tasklist_model>(List, pageindex, pagesize, count);
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.User = User;
                }
                return View(pageList);
            });
        }

        public ActionResult Add()
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.User = User;
                    return View();
                }
            });
        }

        [HttpPost]
        public ActionResult Add(HttpPostedFileBase TaskDll, tb_task_model model, string tempdatajson)
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                string filename = TaskDll.FileName;
                Stream dll = TaskDll.InputStream;
                byte[] dllbyte = new byte[dll.Length];
                dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                tb_task_dal dal = new tb_task_dal();
                tb_version_dal dalversion = new tb_version_dal();
                tb_tempdata_dal tempdatadal = new tb_tempdata_dal();
                //model.taskcreateuserid = Common.GetUserId(this);
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    model.taskcreatetime = DateTime.Now;
                    model.taskversion = 1;
                    int taskid = dal.AddTask(PubConn, model);
                    dalversion.Add(PubConn, new tb_version_model()
                    {
                        taskid = taskid,
                        version = 1,
                        versioncreatetime = DateTime.Now,
                        zipfile = dllbyte,
                        zipfilename = System.IO.Path.GetFileName(filename)
                    });
                    tempdatadal.Add(PubConn, new tb_tempdata_model()
                    {
                        taskid = taskid,
                        tempdatajson = tempdatajson,
                        tempdatalastupdatetime = DateTime.Now
                    });
                }
                return RedirectToAction("index");
            });
        }

        public ActionResult Update(int taskid)
        {
            return this.Visit(EnumUserRole.None, () =>
            {
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    tb_task_dal dal = new tb_task_dal();
                    tb_task_model model = dal.GetOneTask(PubConn, taskid);
                    tb_tempdata_model tempdatamodel = new tb_tempdata_dal().GetByTaskID(PubConn, taskid);
                    List<tb_version_model> Version = new tb_version_dal().GetTaskVersion(PubConn, taskid);
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.Version = Version;
                    ViewBag.User = User;
                    ViewBag.TempData = tempdatamodel;
                    return View(model);
                }
            });
        }

        [HttpPost]
        public ActionResult Update(HttpPostedFileBase TaskDll, tb_task_model model, string tempdatajson)
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                try
                {
                    tb_task_dal dal = new tb_task_dal();
                    tb_version_dal dalversion = new tb_version_dal();
                    tb_tempdata_dal tempdatadal = new tb_tempdata_dal();
                    byte[] dllbyte = null;
                    string filename = "";
                    int change = model.taskversion;
                    if (change == -1)
                    {
                        if (TaskDll == null)
                        {
                            throw new Exception("没有文件！");
                        }
                        filename = TaskDll.FileName;
                        Stream dll = TaskDll.InputStream;
                        dllbyte = new byte[dll.Length];
                        dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                        //model.taskcreateuserid = Common.GetUserId(this);
                    }
                    using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                    {
                        PubConn.Open();
                        var task = dal.GetOneTask(PubConn, model.id);
                        if (task.taskstate == (int)EnumTaskState.Running)
                        {

                            throw new Exception("当前任务在运行中,请停止后提交");
                        }
                        if (change == -1)
                        {
                            model.taskversion = dalversion.GetVersion(PubConn, model.id) + 1;
                        }
                        model.taskupdatetime = DateTime.Now;
                        dal.UpdateTask(PubConn, model);
                        if (change == -1)
                        {
                            dalversion.Add(PubConn, new tb_version_model()
                            {
                                taskid = model.id,
                                version = model.taskversion,
                                versioncreatetime = DateTime.Now,
                                zipfile = dllbyte,
                                zipfilename = System.IO.Path.GetFileName(filename)
                            });
                        }
                        tempdatadal.UpdateByTaskID(PubConn, new tb_tempdata_model()
                        {
                            taskid = model.id,

TaskManager.Web/Views/Node/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
   
</style>
<script>
    function sub() {
        if ($("#nodename").val() == "") {
            alert("请填写节点名称！");
            return false;
        }
        var nodeip = $("#nodeip").val();
        if (nodeip == "") {
            alert("请填写节点IP！");
            return false;
        }
        //else {
        //    //ip地址
        //    var exp = /^(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])$/;
        //    var reg = nodeip.match(exp);
        //    if (reg == null) {
        //        alert("IP地址不合法！");
        //        return false;
        //    }
        //}
    }
</script>
<div class="head">
    <div class="title">
        新增节点 @Html.Raw(TaskManager.Web.Models.Common.HelpHtml(""))
    </div>
</div>
<div>
    @using (Html.BeginForm("Add", "Node", FormMethod.Post, new { @onsubmit = "return sub()" }))
    {
    <ul class="mydetail">
        <li>
            <label>节点名</label><input type="text" id="nodename" name="nodename" />
        </li>
        <li>
            <label>节点ip/host</label><input type="text" id="nodeip" name="nodeip" />
        </li>
        <li>
            <input type="submit" class="btn1" value="提交" />
        </li>
    </ul>
    }
</div>

TaskManager.Web/Views/Node/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<TaskManager.Domain.Model.tb_node_model>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    function Delete(id) {
        $.ajax({
            url: '@Url.Action("Delete", "Node")',
            type: "post",
            data: {
                id: id
            },
            success: function (data) {
                if (data.code == 1) {
                    if (data.state == true) {
                        alert("删除成功！");
                        window.location.reload();
                    }
                    else {
                        alert("删除失败：请确认该节点下的任务已清除！");
                    }
                }
                else {
                    alert(data.msg);
                }
            }
        })
    }
</script>

<div class="head">
    <div class="title">
        节点列表 @Html.Raw(TaskManager.Web.Models.Common.HelpHtml("用于显示任务的执行节点，节点可以分布在不同集群中，在此处列表统一管理和显示。当节点处于状态检查时，会被平台定期扫描，若节点不在运行，会被平台记录到错误日志中，邮件等通知管理员。"))
    </div>
</div>
<div class="orderlist m10 myorder">
   @* @using (Html.BeginForm("index", "Node", new RouteValueDictionary { { "id", "searchForm" } }))
    {
        <div class="item_list">
            <ul>
                <li>
                    <label>创建时间</label><input type="text" class="text" autocomplete="off"name="CStime" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'1900-01-01',readOnly:true})" />
                    至
                <input type="text" class="text" autocomplete="off" name="CEtime" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'1900-01-01',readOnly:true})" />
                </li>
                <li>
                    <label>关键字</label>
                    <input type="text" name="keyword" value="" />
                </li>
                <li>
                    <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
            </ul>
        </div>
    }*@
    <div class="tab_cont">
    <a href="@Url.Action("Add", "Node")" class="btn1">新增</a>
        <div class="list">
            <table>
                <tr>
                    <th>id</th>
                    <th>节点</th>
                    <th>创建时间</th>
                    <th>IP/Host</th>
                    <th>心跳更新时间</th>
                    <th>状态</th>
                    <th>检查心跳状态</th>
                    <th>操作</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.nodename</td>
                        <td>@item.nodecreatetime</td>
                        <td>@item.nodeip</td>
                        <td>@item.nodelastupdatetime</td>
                        <td>
                            @if ((ViewBag.sqldatetimenow - item.nodelastupdatetime) > TimeSpan.FromSeconds(10))
                            { 
                                <span class="stopstate">停止</span>
                            }
                            else
                            {
                                <span class="runstate">运行</span>
                            }
                        </td>
                        <td>@(Convert.ToBoolean(item.ifcheckstate) == true ? "是" : "否")</td>
                        <td>
                            <a href="@Url.Action("Update", "Node", new { id = @item.id })">修改</a>
                            <input type="button" value="删除" onclick="Delete('@item.id    ')" />
                            <a href="@Url.Action("Index", "Task", new { nodeid = @item.id })">查看任务</a>
                        </td>
                    </tr>
                }
            </table>
            <div class="total pt10">
                <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
                @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.TextBox, CssClass = "mvcPager"  })
            </div>
        </div>
    </div>
</div>

TaskManager.Web/Views/Node/Update.cshtml
@model TaskManager.Domain.Model.tb_node_model
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    function sub() {
        if ($("#nodename").val() == "") {
            alert("请填写节点名称！");
            return false;
        }
        var nodeip = $("#nodeip").val();
        if (nodeip == "") {
            alert("请填写节点IP！");
            return false;
        }
        //else {
        //    //ip地址
        //    var exp = /^(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])$/;
        //    var reg = nodeip.match(exp);
        //    if (reg == null) {
        //        alert("IP地址不合法！");
        //        return false;
        //    }
        //}
    }
</script>
<div class="head">
    <div class="title">
        修改节点 @Html.Raw(TaskManager.Web.Models.Common.HelpHtml(""))
    </div>
</div>
<div>
    <input type="hidden" value="@Model.id" id="id" />
    @using (Html.BeginForm("Update", "Node", FormMethod.Post, new { @onsubmit = "return sub()" }))
    {
    <ul  class="mydetail">
        <li>
            <label>节点名</label><span><input type="text" id="nodename" name="nodename" value="@Model.nodename" /></span>
        </li>
        <li>
            <label>节点ip/host</label><input type="text" id="nodeip" name="nodeip" value="@Model.nodeip" />
        </li>
        <li>
            <label>是否检测节点状态</label><input type="checkbox" id="ifcheckstate" name="ifcheckstate" value="@(Model.ifcheckstate.ToString())" @(Model.ifcheckstate==true?"checked=checked":"") onclick=" $(this).val($(this).is(':checked'));"  />(若开启，若检测到节点停止，则发邮件)
            <script type="text/javascript">
            </script>
        <li>
            <input type="submit" class="btn1" value="提交" />
        </li>
    </ul>
    }
</div>