TaskManager.Web/Controllers/PerformanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Domain.Dal;
using TaskManager.Domain.Model;
using TaskManager.Web.Models;
using Webdiyer.WebControls.Mvc;
using BSF.Db;
using TaskManager.Core;

namespace TaskManager.Web.Controllers
{
    public class PerformanceController : BaseWebController
    {
        //
        // GET: /Performance/

        public ActionResult Index(string nodeid, string taskid, string orderby)
        {
            return this.Visit(EnumUserRole.None, () =>
            {
                ViewBag.nodeid = nodeid;
                ViewBag.taskid = taskid;
                ViewBag.orderby = orderby;
                tb_performance_dal dal = new tb_performance_dal();
                
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    ViewBag.taskmodels = dal.GetAllWithTask(PubConn,nodeid,taskid,orderby,DateTime.Now.AddMinutes(-10));
                   
                }
                return View();
            });
        }
        public ActionResult NodeIndex()
        {
            return this.Visit(EnumUserRole.None, () =>
            {
                tb_performance_dal dal = new tb_performance_dal();
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    ViewBag.nodemodels = dal.GetAllWithNode(PubConn, "p.nodeid desc", DateTime.Now.AddMinutes(-10));
                }
                return View();
            });
        }
    }
}

TaskManager.Web/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Domain.Model;
using TaskManager.Domain.Dal;
using BSF.Db;
using TaskManager.Web.Models;
using Webdiyer.WebControls.Mvc;
using System.Drawing;
using System.IO;
using TaskManager.Core;
using BSF.Extensions;
using Newtonsoft.Json;
using TaskManager.Core;
using TaskManager.Web.Tools;

namespace TaskManager.Web.Controllers
{
    [AuthorityCheck]
    public class TaskController : BaseWebController
    {
        //
        // GET: /Task/

        public ActionResult Index(string taskid, string keyword, string CStime, string CEtime, int categoryid = -1, int nodeid = -1, int userid = -1, int state = -999, int pagesize = 10, int pageindex = 1)
        {
            return this.Visit(EnumUserRole.None, () =>
            {
                #region 保存查询信息,优化操作体验
                var ps = Request.RequestParams();
                ps.Remove("userid");
                var sessionkey = "/task/index/";
                if (ps.Count == 0)
                {
                    if (Session[sessionkey] != null)
                    {
                        var ks = new BSF.Serialization.JsonProvider( BSF.Serialization.JsonAdapter.EnumJsonMode.Newtonsoft).Deserialize<List<KeyValuePair<string,object>>>(Session[sessionkey] as string);
                        foreach (var k in ks)
                        {
                            if(!ViewData.ContainsKey(k.Key))
                                ViewData.Add(k);
                        }
                        taskid = (string)ViewBag.taskid;
                        keyword =(string) ViewBag.keyword;
                        CStime = (string)ViewBag.CStime;
                        CEtime = (string) ViewBag.CEtime;
                        categoryid = (int)ViewBag.categoryid;
                        nodeid = (int)ViewBag.nodeid;
                        userid = (int)ViewBag.userid;
                        state = (int)ViewBag.state;
                        pagesize = (int)ViewBag.pagesize;
                        pageindex = (int)ViewBag.pageindex;
                    }
                }
                ViewBag.taskid = taskid;
                ViewBag.keyword = keyword;
                ViewBag.CStime = CStime;
                ViewBag.CEtime = CEtime;
                ViewBag.categoryid = categoryid;
                ViewBag.nodeid = nodeid;
                ViewBag.userid = userid;
                ViewBag.state = state;
                ViewBag.pagesize = pagesize;
                ViewBag.pageindex = pageindex;

                Session[sessionkey] = new BSF.Serialization.JsonProvider().Serializer(ViewData);
                #endregion

                tb_task_dal dal = new tb_task_dal();
                PagedList<tb_tasklist_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_tasklist_model> List = dal.GetList(PubConn, taskid, keyword, CStime, CEtime, categoryid, nodeid, userid, state, pagesize, pageindex, out count);
                    pageList = new PagedList<tb_tasklist_model>(List, pageindex, pagesize, count);
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.User = User;
                }
                return View(pageList);
            });
        }

        public ActionResult Add()
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.User = User;
                    return View();
                }
            });
        }

        [HttpPost]
        public ActionResult Add(HttpPostedFileBase TaskDll, tb_task_model model, string tempdatajson)
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                string filename = TaskDll.FileName;
                Stream dll = TaskDll.InputStream;
                byte[] dllbyte = new byte[dll.Length];
                dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                tb_task_dal dal = new tb_task_dal();
                tb_version_dal dalversion = new tb_version_dal();
                tb_tempdata_dal tempdatadal = new tb_tempdata_dal();
                //model.taskcreateuserid = Common.GetUserId(this);
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    model.taskcreatetime = DateTime.Now;
                    model.taskversion = 1;
                    int taskid = dal.AddTask(PubConn, model);
                    dalversion.Add(PubConn, new tb_version_model()
                    {
                        taskid = taskid,
                        version = 1,
                        versioncreatetime = DateTime.Now,
                        zipfile = dllbyte,
                        zipfilename = System.IO.Path.GetFileName(filename)
                    });
                    tempdatadal.Add(PubConn, new tb_tempdata_model()
                    {
                        taskid = taskid,
                        tempdatajson = tempdatajson,
                        tempdatalastupdatetime = DateTime.Now
                    });
                }
                return RedirectToAction("index");
            });
        }

        public ActionResult Update(int taskid)
        {
            return this.Visit(EnumUserRole.None, () =>
            {
                using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    tb_task_dal dal = new tb_task_dal();
                    tb_task_model model = dal.GetOneTask(PubConn, taskid);
                    tb_tempdata_model tempdatamodel = new tb_tempdata_dal().GetByTaskID(PubConn, taskid);
                    List<tb_version_model> Version = new tb_version_dal().GetTaskVersion(PubConn, taskid);
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.Version = Version;
                    ViewBag.User = User;
                    ViewBag.TempData = tempdatamodel;
                    return View(model);
                }
            });
        }

        [HttpPost]
        public ActionResult Update(HttpPostedFileBase TaskDll, tb_task_model model, string tempdatajson)
        {
            return this.Visit(EnumUserRole.Admin, () =>
            {
                try
                {
                    tb_task_dal dal = new tb_task_dal();
                    tb_version_dal dalversion = new tb_version_dal();
                    tb_tempdata_dal tempdatadal = new tb_tempdata_dal();
                    byte[] dllbyte = null;
                    string filename = "";
                    int change = model.taskversion;
                    if (change == -1)
                    {
                        if (TaskDll == null)
                        {
                            throw new Exception("没有文件！");
                        }
                        filename = TaskDll.FileName;
                        Stream dll = TaskDll.InputStream;
                        dllbyte = new byte[dll.Length];
                        dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                        //model.taskcreateuserid = Common.GetUserId(this);
                    }
                    using (DbConn PubConn = DbConn.CreateConn(Config.TaskConnectString))
                    {
                        PubConn.Open();
                        var task = dal.GetOneTask(PubConn, model.id);
                        if (task.taskstate == (int)EnumTaskState.Running)
                        {

                            throw new Exception("当前任务在运行中,请停止后提交");
                        }
                        if (change == -1)
                        {
                            model.taskversion = dalversion.GetVersion(PubConn, model.id) + 1;
                        }
                        model.taskupdatetime = DateTime.Now;
                        dal.UpdateTask(PubConn, model);
                        if (change == -1)
                        {
                            dalversion.Add(PubConn, new tb_version_model()
                            {
                                taskid = model.id,
                                version = model.taskversion,
                                versioncreatetime = DateTime.Now,
                                zipfile = dllbyte,
                                zipfilename = System.IO.Path.GetFileName(filename)
                            });
                        }
                        tempdatadal.UpdateByTaskID(PubConn, new tb_tempdata_model()
                        {
                            taskid = model.id,

TaskManager.Web/Views/Performance/Index.cshtml
@model List<TaskManager.Domain.Model.tb_performance_model>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var TaskModels = ViewBag.taskmodels as List<TaskManager.Domain.Model.tb_performanceinfo_model>;
}

<div class="head">
    <div class="title">
        当前任务性能 @Html.Raw(TaskManager.Web.Models.Common.HelpHtml("根据每个任务的cpu，内存等定期通知到任务调度平台，便于管理员管理任务的执行性能。目前只显示当前的内存情况。"))
    </div>
</div>
<div class="orderlist m10 myorder">
      @using (Html.BeginForm("index", "Performance",FormMethod.Get  ))
    {
        <div class="item_list">
            <ul>
                <li>
                    <label>任务id</label>
                    <input type="text" name="taskid" value="@(string.IsNullOrEmpty(ViewBag.taskid)?"":ViewBag.taskid)" />
                </li>
                <li>
                    <label>节点id</label>
                    <input type="text" name="nodeid" value="@(string.IsNullOrEmpty(ViewBag.nodeid)?"":ViewBag.nodeid)" />
                </li>
                <li>
                    <label>排序</label>
                    <select name="orderby">
                        <option value="">请选择</option>
                        <option value="cpu desc"  @(ViewBag.orderby=="cpu desc"?"selected='selected'":"")>Cpu降序</option>
                        <option value="memory desc"  @(ViewBag.orderby=="memory desc"?"selected='selected'":"")>Memory降序</option>
                        <option value="installdirsize desc"  @(ViewBag.orderby=="installdirsize desc"?"selected='selected'":"")>应用大小降序</option>
                    </select>
                </li>
                <li>
                    <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
            </ul>
        </div>
    }
    <div class="tab_cont">
        <div class="list">
            <table>
                <tr>
                    <th>id</th>
                    <th>任务</th>
                    <th>节点</th>
                    <th>Cpu(总cpu时间 s)</th>
                    <th>内存(M)</th>
                    <th>应用大小(M)</th>
                    <th>最后更新时间</th>
                </tr>
                @foreach (var item in TaskModels)
                {
                    <tr>
                        <td>@item.model.id</td>
                        <td><a href="@Url.Action("Index", "Task", new { taskid =item.model.taskid })">@item.taskname [@item.model.taskid]</a></td>
                        <td>@item.nodename [@item.model.nodeid]</td>
                        <td>@item.model.cpu.ToString("f2") (s)</td>
                        <td>@item.model.memory.ToString("f2") (M)</td>
                        <td>@item.model.installdirsize.ToString("f2") (M)</td>
                         <td>@item.model.lastupdatetime</td>
                    </tr>
                }
            </table>
        </div>
        
    </div>
</div>

TaskManager.Web/Views/Performance/NodeIndex.cshtml
@{
    ViewBag.Title = "NodeIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var NodeModels = ViewBag.nodemodels as List<TaskManager.Domain.Model.tb_performanceinfo_model>;
}

<div class="head">
    <div class="title">
        当前节点性能 @Html.Raw(TaskManager.Web.Models.Common.HelpHtml("用于统计当前节点上所有任务的cpu，内存等性能，非实际的节点性能，仅用于参考。后续可以改进。"))
    </div>
</div>
<div class="orderlist m10 myorder">
    <div class="tab_cont">
       <div class="list">
            <table>
                <tr>
                    <th>节点</th>
                    <th>Cpu(总用cpu时间 s)</th>
                    <th>内存(M)</th>
                    <th>应用大小(M)</th>
                    <th>最后更新时间</th>
                </tr>
                @foreach (var item in NodeModels)
                {
                    <tr>
                        
                        <td>@item.nodename [@item.model.nodeid]</td>
                        <td>@item.model.cpu.ToString("f2") (s)</td>
                        <td>@item.model.memory.ToString("f2") (M)</td>
                        <td>@item.model.installdirsize.ToString("f2") (M)</td>
                         <td>@item.model.lastupdatetime</td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>